CREATE TYPE priority_enum AS ENUM ('baja', 'media', 'alta');

CREATE TYPE location_enum AS ENUM (
  'Operadora de Servicios Alimenticios',
  'Adrian Tropical 27',
  'Adrian Tropical Malecón',
  'Adrian Tropical Lincoln',
  'Adrian Tropical San Vicente',
  'Atracciones el Lago',
  'M7',
  'E. Arturo Trading',
  'Edificio Comunitario'
);

CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  is_urgent boolean NOT NULL,
  priority priority_enum NOT NULL,
  requester text NOT NULL,
  location location_enum NOT NULL,
  assignee text NOT NULL,
  incident_date date NOT NULL,
  deadline_date date,
  image text NOT NULL,
  email text,
  phone text,
  comments text,
  created_at timestamp DEFAULT now() NOT NULL,
  status TEXT DEFAULT 'Pendiente'
);